Use yaml.safe_load() instead of plain .load()
Apart from the fact that it's much safer, it also fixes compatibility
with newer pyyaml, which explicitly requires the `Loader` argument:

```
Traceback (most recent call last):
  File "/usr/bin/coveralls", line 33, in <module>
    sys.exit(load_entry_point('cpp-coveralls==0.4.2', 'console_scripts', 'coveralls')())
  File "/usr/lib/python3.10/site-packages/cpp_coveralls/__init__.py", line 67, in run
    yml = parse_yaml_config(args)
  File "/usr/lib/python3.10/site-packages/cpp_coveralls/__init__.py", line 49, in parse_yaml_config
    yml = yaml.load(fp)
TypeError: load() missing 1 required positional argument: 'Loader'
```